In [ ]:
""" Uso de LLMs e verificação de autenticidade (itens 6, 9 e 10)


#Segundo  o software gratuito No Plagio, nosso código deu:  17% conteúdo de IA, 5% de plágio e 0% de plágio traduzido de outros línguas.

#Segundo o software gratuito JustDone, nosso código deu 7% de plágio.

#Segundo o software gratuito gptZero, nosso código deu 20% conteúdo de IA.

#     Os resultados acima estão totalmente ligados ao uso das LLMs ChatGPT e Gemini, que usamos para ajudar a fazer os menus interativos,
#     que dão a opção de botar um arquivo do próprio usuário ou escolher matrizes automáticas, matrizes estas que também pedimos para que eles gerassem os valores,
#     para que os resultados dessem seguros, verificados e não muito grandes e ajuda com as hipóteses e justificativas que poderíamos fazer para cada questão.
#     Como as IAs dão respostas de conteúdos que já existem, através do seu deep learning e treinamento de generalização, os resultados dos softwares acima são
#     totalmente previsíveis e verídicos.

"""


In [ ]:
""" Hipóteses e justificativas


1. Hipóteses para os Métodos de Resolução de Sistemas e Fatoração (Questão 1)


1.1) Substituição para Trás (Backward Substitution) e para Frente (Forward Substitution)

Hipótese: Para a substituição para trás, a matriz deve ser triangular superior (U).
Para a substituição para frente, deve ser triangular inferior (L). Além disso, todos os elementos da diagonal principal devem ser diferentes de zero (uii != 0 e lii != 0).

Justificativa: O algoritmo realiza divisões sucessivas pelos elementos da diagonal. Se houver um zero na diagonal, ocorrerá um erro de divisão por zero.

Impacto: Sem essa hipótese, o código falha e interrompe a execução com um erro de ZeroDivisionError.



1.2) Fatoração LU (Sem pivotamento)

Hipótese: A matriz A deve ser quadrada (n x n) e todas as suas submatrizes principais líderes devem ser não-singulares (determinante diferente de zero).

Justificativa: Se uma submatriz principal líder for singular, o algoritmo tentará realizar uma divisão por zero ao calcular os multiplicadores da eliminação gaussiana.

Impacto: Se não for atendida, o algoritmo falha no meio do processo de eliminação. Se for necessário lidar com matrizes genéricas, seria preciso adotar a
Fatoração LUP (com pivotamento parcial), mas sem pivotamento, essa hipótese é estrita.



1.3) Métodos Iterativos: Jacobi e Gauss-Seidel

Hipótese: A matriz A deve ser estritamente diagonal dominante (o valor absoluto do elemento da diagonal é maior que a soma dos valores absolutos dos outros elementos
da mesma linha) ou ser simétrica e positiva definida.

Justificativa: Essas são condições suficientes para garantir a convergência dos métodos iterativos para qualquer vetor inicial (x^0).

Impacto: Se a matriz não cumprir essas condições, o algoritmo pode divergir, fazendo com que as aproximações tendam ao infinito em vez de chegarem à solução real
do sistema Ax = b.





2. Hipóteses para o Gerador de Sudoku (Questão 2)


2.1) Existência de Solução Única (Validade do Tabuleiro)

Hipótese: Todo tabuleiro gerado pelo algoritmo para o usuário deve possuir uma, e apenas uma, solução válida.

Justificativa: Um jogo de Sudoku apropriado não pode ter múltiplas respostas corretas e nem ser impossível de resolver. Para garantir isso, o algoritmo de geração
geralmente começa com uma matriz completamente preenchida e válida, e vai removendo elementos ("pistas") de forma simétrica ou aleatória, testando a unicidade da
solução a cada remoção através de um algoritmo de backtracking ou por regras lógicas.

Impacto: Se essa hipótese não for garantida pelo código, o usuário pode receber um jogo incompleto que possui várias respostas certas (o que invalida a lógica do jogo)
ou um jogo travado (sem solução possível).



2.2) Preenchimento por Blocos e Restrições Matriciais

Hipótese: A estrutura do jogo é modelada como uma matriz A de ordem 9 x 9, subdividida em 9 submatrizes (blocos) de ordem 3 x 3. A hipótese fundamental do algoritmo é
que cada linha, cada coluna e cada um dos 9 blocos deve conter uma permutação dos números de 1 a 9, sem repetições.

Justificativa: Essa é a regra matemática que define o espaço de busca do algoritmo. Ao gerar a matriz inicial gabaritada, o algoritmo deve validar simultaneamente essas
três restrições para cada elemento aij inserido.

Impacto: O não cumprimento estrito dessas restrições durante a fase de geração faz com que o gabarito gerado pelo sistema seja inválido.



2.3) Quantidade Mínima de Pistas (Dificuldade do Jogo)

Hipótese: O algoritmo assume uma quantidade predefinida (ou escolhida pelo usuário) de números visíveis iniciais (pistas). Matematicamente, está provado que o número
mínimo absoluto de pistas para que um Sudoku clássico 9 x 9 tenha uma solução única é 17.

Justificativa: Se o algoritmo remover números demais e deixar o tabuleiro com menos de 17 pistas, é matematicamente impossível garantir uma solução única.

Impacto: Definir faixas de pistas (ex: Facil = 40 pistas, Médio = 32 pistas, Difícil = 24 pistas) altera a complexidade computacional do algoritmo de geração e o tempo
de processamento necessário para verificar se a solução continua única.







3. O Algoritmo KNN (K-Nearest Neighbors) (Questão 3)


Hipóteses:

3.1) Os dados numéricos de entrada na planilha do Excel estão na mesma escala (ou foram previamente normalizados/padronizados).

3.2) A última coluna contém valores categóricos ou discretos bem definidos para os rótulos.

Justificativa: O KNN é baseado no cálculo de distâncias (como a Euclidiana, Manhattan, etc.). Se uma variável tiver uma escala muito maior que as outras
(ex: Salário vs. Idade), ela dominará completamente o cálculo da distância, tornando as outras variáveis irrelevantes.

Impacto: Se os dados não forem normalizados, o KNN gerará predições enviesadas e imprecisas. Além disso, se houver dados faltantes (nan) nas colunas, o cálculo da
distância falhará.






4. Hipóteses para Autovalores e Métodos de Potência (Questão 4)


4.1) Avaliação de Autovetores

Hipótese: Os vetores b e c fornecidos pelo usuário devem ser vetores não-nulos (v != 0).

Justificativa: Por definição matemática, o vetor nulo não pode ser um autovetor, pois a equação A.0 = lambda.0 é trivialmente verdadeira
para qualquer escalar lambda.

Impacto: Se o usuário passar um vetor de zeros, o algoritmo deve rejeitá-lo como autovetor para manter a consistência matemática.



4.2) Método da Potência

Hipóteses:

4.2.1) A matriz A deve ser quadrada (n x n) e possuir um autovalor estritamente dominante em módulo (|lambda_1| > |lambda_2| > ... > |lambda_n|).

4.2.2) O vetor inicial (geralmente uma aproximação ou o próprio vetor b ou c) não deve ser ortogonal ao autovetor associado ao autovalor dominante.

Justificativa: O método baseia-se em multiplicações sucessivas da matriz pelo vetor. Se o maior autovalor estiver empatado em módulo com outro (ex: lambda_1 = 5
e lambda_2 = -5), o algoritmo vai oscilar e não convergirá. Se o vetor inicial for ortogonal, o método convergirá para o segundo maior autovalor.

Impacto: Se as hipóteses não forem atendidas, o método da potência não convergirá para o autovalor dominante real, resultando em valores errados ou loops infinitos
de iteração sem estabilização.

"""


In [ ]:
""" Formato dos dados de entrada e de saída (itens 3 e 4)


Como o código de cada questão estão em blocos diferentes, para colocar as entradas de cada questão deve-se estar rodando apenas o código da questão desejada, para que
não haja confusão na hora de inserir o arquivo através do menu da questão.
É possível que cada código já esteja com um terminal aberto e certas matrizes nela, mas é o histórico da rodagem do código. Para rodar do zero, basta clicar no play.



Formatos de entrada e saída (questão 1):

O algoritmo processa todas as estruturas necessárias para a resolução a partir de um único arquivo Excel (.xlsx), utilizando um mapeamento dinâmico baseado nos cabeçalhos
das colunas.

Matriz A (A_col1, A_col2, ...): Armazena as colunas da matriz de coeficientes do sistema. Deve ser obrigatoriamente quadrada (n x n). De maneira análoga, teremos a Matriz P.

Vetor b: Coluna com os termos independentes do sistema Ax=b. Deve conter exatamente n elementos. De maneira análoga, teremos o vetor c.
Parâmetros Gerais (x0, tolerancia, max_iter): Vetor de aproximação inicial (n elementos), tolerância numérica e limite máximo de iterações para os métodos de Jacobi e
Gauss-Seidel.

As saídas serão demonstradas no terminal de execução, com os resultados para cada algoritmo sendo representados e nomeados adequadamente.




Formatos de entrada (questão 2):

Os dados de entrada estão organizados em uma planilha do Exel, com seus valores normalmente numerados em uma tabela 9x9, pois o algoritmo do Sudoku suporta matrizes
apenas neste formato.

As saídas serão representadas no terminal, com o gabarito do tabuleiro completo, representado pela execução perfeita do algoritmo de realização do Sudoku.




Formatos de entrada e saída (questão 3):

Os dados de entrada podem ser fornecidos de duas formas: por meio de um arquivo Excel (.xlsx) enviado pelo usuário ou por um conjunto de dados simulados gerados automatica-
mente pelo sistema. Em ambos os casos, a estrutura dos dados segue o formato de uma matriz de atributos acompanhada por um vetor de classes.

A matriz de atributos X é composta por n instâncias e m características numéricas, sendo representada como colunas do DataFrame (Caracteristica_1, Caracteristica_2, ...,
Caracteristica_m). A última coluna do arquivo representa o vetor de classes, contendo os rótulos associados a cada instância.

O algoritmo KNN exige que o conjunto de dados contenha pelo menos duas colunas (atributos e classe) e que o número de instâncias seja maior ou igual ao valor de k.
Neste trabalho, como o valor de k foi fixado em 3, o conjunto de dados deve conter no mínimo 3 instâncias de treinamento.

As saídas são apresentadas no terminal de execução, exibindo para cada ponto de teste a classe prevista pelo algoritmo KNN para cada uma das métricas de distância
utilizadas. Também são exibidos os dados carregados e os pontos de teste avaliados.




Formatos de entrada e saída (questão 4):


Os dados de entrada são fornecidos por meio de um arquivo Excel (.xlsx) contendo múltiplas abas nomeadas de forma fixa: Matriz_A, Matriz_P, Vetor_b e Vetor_c, ou alterna-
tivamente por um conjunto de dados simulados pré-definidos no código.


A Matriz A e a Matriz P representam matrizes quadradas de dimensão n × n, sendo utilizadas para operações envolvendo autovalores e autovetores. O sistema exige obrigatoria-
mente que ambas sejam quadradas para garantir a validade dos métodos numéricos aplicados.

Os vetores b e c representam vetores coluna de dimensão n, utilizados na verificação de autovetores associados a um valor de lambda fornecido pelo usuário. O valor de lambda
é inserido manualmente durante a execução do programa e deve ser um número real válido.

As saídas são apresentadas no terminal de execução e incluem: o polinômio característico das matrizes A e P; a verificação de autovetores para os vetores b e c em relação
ao valor de lambda informado; o autovalor dominante aproximado e o autovetor correspondente obtido pelo Método da Potência.



"""

In [ ]:
""" Testes Rigorosos (item 7)

Testes para dados incompatíveis (questão 1)
Abaixo, dois testes feitos sobre arquivos de matrizes de dados incompatíveis, de acordo com as hipóteses dos algoritmos requeridos e suas respectivas saídas:

TESTE 1:

Matriz A extraída:
 [5 2]
 [1 7]
 [3 1]

Vetor b extraído: [  6.  25. -11.]

Matriz P extraída:
 [1 0]
 [0 1]
 [0 0]

Vetor c extraído: [1 1 1]
--------------------------------------------------
Configurações adotadas -> Tolerância: 1.0 | Máx. Iterações: 100
Vetor inicial x0 utilizado:
 [0. 0. 0.]

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE FORMATO] A matriz A precisa ser quadrada (n x n).
Dimensão da matriz enviada: (3, 2).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

TESTE 2:

Matriz A extraída:
 [8  1 -1]
 [1  7  5]
 [3  1  4]
 [0  0  5]

Vetor b extraído: [  6.  25. -11.]

Matriz P extraída:
 [1 0]
 [0 1]
 [0 0]

Vetor c extraído: [1 1 1]
--------------------------------------------------
Configurações adotadas -> Tolerância: 1.0 | Máx. Iterações: 100
Vetor inicial x0 utilizado:
 [0. 0. 0.]


Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE FORMATO] A matriz A precisa ser quadrada (n x n).
Dimensão da matriz enviada: (4, 3).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!



Testes para dados incompatíveis (questão 2):
Abaixo, dois testes feitos sobre arquivos de dados de matrizes incompatíveis com
o tamanho usual de um tabuleiro de Sudoku (9x9) e sobre incompatibilidades com regras do
jogo e suas respectivas saídas:


********************************************************************************
TESTE 1:
Matriz extraida:
[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]
[0 0 2 3 0 0 4]
[0 0 1 8 0 0 0]
[0 6 0 0 7 0 0]
[0 0 0 0 0 9 0]
[0 0 0 5 0 0 6]
[7 0 0 0 0 0 0]
[0 0 8 0 0 2 0]


Saída:
[ERRO DE TAMANHO] Formato inválido! O arquivo contém dimensões (10, 7), mas deve
ser obrigatoriamente uma matriz 9x9.
********************************************************************************


********************************************************************************
TESTE 2:
Matriz extraida:
[0 0 0 5 0 1 1 2]
[0 0 0 0 0 0 0 3]
[0 0 2 3 0 0 0 4]
[0 0 1 8 0 0 0 5]
[0 6 0 0 7 0 0 0]
[0 0 0 0 0 9 0 0]
[0 0 0 5 0 0 0 6]
[7 0 0 0 0 0 0 0]
[0 0 8 0 0 2 0 0]

Saída:
[ERRO DE REGRA] O tabuleiro enviado quebra as regras do Sudoku!
O número 5 na posição (Linha 1, Coluna 4) colide com outra pista idêntica.
********************************************************************************


Testes para dados incompatíveis (questão 3):
Abaixo, três testes aplicados à questão 3, entrando com uma planilha sem dados,
uma planilha com dados incompatíveis e com uma planilha com dados faltantes.


*******************************************************************************
TESTE 1 (Sem dados na planilha):
Dados extraídos: NULO

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE DADOS] A planilha está vazia.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE FORMATO]
A planilha deve possuir pelo menos:
- 1 coluna de atributos
- 1 coluna de classe
Dimensão encontrada: (0, 0)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
********************************************************************************


********************************************************************************
TESTE 2 (String nos dados):
Dados extraídos:
Caracteristica_1: [1, abc, 3]
Caracteristica_2: [2, 4, 5]
Classe: [0, 1, 0]

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE FORMATO]
A planilha deve possuir pelo menos:
- 1 coluna de atributos
- 1 coluna de classe
Dimensão encontrada: (2, 1)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE DADOS]
São necessários pelo menos 3 exemplos para executar o KNN com k=3.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
********************************************************************************


********************************************************************************
TESTE 3 (sem atributos)
Dados extraídos:
Classe: [0, 1, 0, 0]

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE DADOS]
São necessários pelo menos 3 exemplos para executar o KNN com k=3.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE CONFIGURAÇÃO]
k = 3
Número de amostras = 1
k não pode ser maior que a quantidade
de exemplos de treinamento.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
********************************************************************************


Testes para dados incompatíveis (questão 4):
Abaixo, dois testes para entradas de dados incongruentes com o formato esperado
para a execução do algoritmo.


********************************************************************************
TESTE 1(Vetor b incompatível com matriz A):
Matrizes e vetores de entrada:
Matriz A:
[[ 1  0  0]
 [ 0  2  0]
 [ 0  0  3]]

Vetor b:
[ 1  0]

Matriz P:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]]

Vetor c:
[ 0  1  0]

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE DIMENSÃO]
O vetor b possui tamanho incompatível
com a matriz A.
Dimensão de A: (3, 3)
Tamanho de b: 2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
********************************************************************************

********************************************************************************
TESTE 2(Matriz não quadrada)
Matrizes e vetores de entrada:
Matriz A:
[[ 1  2]
 [ 3  4]
 [ 5  6]]

Vetor b:
[ 1  0  0]

Matriz P:
[[ 1  0  0]
 [ 0  1  0]
 [ 0  0  1]]

Vetor c:
[ 0  1  0]

Saída:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
[ERRO DE FORMATO]
A matriz A precisa ser quadrada (n x n).
Dimensão encontrada: (3, 2)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
********************************************************************************
"""

In [ ]:
# Importando bibliotecas que possuem funções que manipulam dados de planilhas e dados numéricos

import pandas as pd # Para trabalhar com dados de entradas salvo nas planilhas. Cada função utilizada será no formato um pd.funcao()
import numpy as np # Para trabalhar com a manipulação de dados numéricos. Cada função será no formato np.funcao()
from google.colab import files  # Garante a importação da biblioteca de upload

# =====================================================================
# FUNÇÕES DE VALIDAÇÃO E ERROS (FORMATO E ESPECIFICAÇÕES)
# =====================================================================

def validar_dados_sistema(A, b, P, c):
    """
    Função auxiliar para validar se a matriz e vetores enviados por upload
    estão condizentes com o formato esperado e exigido pela Questão 1.
    """
    # Verifica se a matriz A é bidimensional e quadrada
    if len(A.shape) != 2 or A.shape[0] != A.shape[1]:
        raise ValueError(
            f"[ERRO DE FORMATO] A matriz A precisa ser quadrada (n x n).\n"
            f"Dimensão da matriz enviada: {A.shape}."
        )

    n = A.shape[0]

    # Verifica se o tamanho do vetor b é compatível com a matriz A
    if len(b) != n:
        raise ValueError(
            f"[ERRO DE DIMENSÃO] O vetor b deve ter o mesmo tamanho do sistema ({n}).\n"
            f"Tamanho do vetor b enviado: {len(b)}."
        )

    # Verifica se a matriz P possui as mesmas dimensões de A
    if P.shape != (n, n):
        raise ValueError(
            f"[ERRO DE DIMENSÃO] A matriz P deve ser quadrada e ter a mesma dimensão de A ({n}x{n}).\n"
            f"Dimensão da matriz P enviada: {P.shape}."
        )

    # Verifica se o tamanho do vetor c é compatível
    if len(c) != n:
        raise ValueError(
            f"[ERRO DE DIMENSÃO] O vetor c deve ter o mesmo tamanho do sistema ({n}).\n"
            f"Tamanho do vetor c enviado: {len(c)}."
        )

    print("[VALIDAÇÃO] Sucesso: Matrizes e vetores possuem dimensões válidas e alinhadas.")

    # Critério de convergência das linhas para os métodos iterativos
    diagonal_dominante = True
    for i in range(n):
        soma_linha = sum(np.abs(A[i, j]) for j in range(n) if i != j)
        if np.abs(A[i, i]) <= soma_linha:
            diagonal_dominante = False
            break

    if not diagonal_dominante:
        print("\n[AVISO DE CONVERGÊNCIA] A matriz A não é estritamente diagonal dominante.")
        print("Os métodos de Jacobi e Gauss-Seidel podem divergir para estes dados.")
    else:
        print("[VALIDAÇÃO] A matriz A é estritamente diagonal dominante (Convergência garantida).")


# =====================================================================
# ALGORITMOS DE ÁLGEBRA LINEAR COMPUTACIONAL
# =====================================================================

# Fatoração LU real para decompor a matriz A em L e U de verdade
def fatoracao_lu(A):
    n = A.shape[0]
    L = np.eye(n, dtype=float)
    U = A.copy().astype(float)

    for i in range(n):
        if U[i, i] == 0:
            raise ValueError(f"[ERRO MATEMÁTICO] Pivô nulo encontrado na diagonal na posição ({i},{i}). Fatoração LU abortada.")
        for j in range(i + 1, n):
            fator = U[j, i] / U[i, i]
            L[j, i] = fator
            U[j, i:] -= fator * U[i, i:]

    return L, U

# Função para algoritmo de substituição para frente
def substituicao_para_frente(L, b):

    # Identifica o tamanho do sistema (número de equações)
    n = len(b)

    # Aloca um vetor na memória com n posições preenchidas por 0 no tipo float
    x = np.zeros(n, dtype=float)

    # percorre linha por linha do sistema (de 0 até n-1)
    for i in range(n):
        somatorio = 0.0  # Zera o acumulador de termos conhecidos para a linha atual

        # loop interno ao que percorre as linhas e que multiplica os coeficientes anteriores pelos x que já descobrimos
        for j in range(i):
            somatorio += L[i, j] * x[j]

        # Isola a incógnita x[i], subtraindo o somatório de b[i] e dividindo pela diagonal L[i, i]
        x[i] = (b[i] - somatorio) / L[i, i]

    # Retorna o vetor x completamente preenchido com as soluções do sistema
    return x


# Função para o algoritmo do método de substituição para trás
def substituicao_para_tras(U, b):
    # Identifica o tamanho do sistema (número de equações)
    n = len(b)

    # Aloca um vetor na memória com n posições preenchidas por 0 no tipo float
    x = np.zeros(n, dtype=float)

    # Percorre as linhas do sistema em ordem reversa (da última linha até a linha 0)
    for i in range(n - 1, -1, -1):
        somatorio = 0.0  # Zera o acumulador de termos conhecidos para a linha atual

        # Loop interno que percorre as colunas posteriores à diagonal para multiplicar os coeficientes pelos x já descobertos
        for j in range(i + 1, n):
            somatorio += U[i, j] * x[j]

        # Verifica se o elemento da diagonal principal é zero para evitar divisão por zero
        if U[i, i] == 0:
            raise ValueError("Zero na diagonal de U.")

        # Isola a incógnita x[i], subtraindo o somatório de b[i] e dividindo pela diagonal U[i, i]
        x[i] = (b[i] - somatorio) / U[i, i]

    # Retorna o vetor x completamente preenchido com as soluções do sistema
    return x


# Função para o método de Jacobi
def metodo_jacobi(A, b, x0, tol=1e-5, max_iter=100):

    # Identifica o número de equações e variáveis do sistema
    n = len(b)

    # Cria uma cópia inicial do vetor de aproximação fornecido pelo usuário
    x = x0.copy()

    # Inicia o laço de iterações do método computacional
    for k in range(max_iter):
        # Aloca na memória um vetor temporário para armazenar as novas aproximações desta iteração
        x_novo = np.zeros(n, dtype=float)

        # Percorre linha por linha da matriz do sistema
        for i in range(n):
            # Inicializa o acumulador para o somatório dos termos conhecidos (A[i, j] * x[j])
            somatorio = 0.0

            # Percorre todas as colunas da linha atual para calcular o somatório
            for j in range(n):
                # Ignora o elemento da diagonal principal (i == j) no somatório
                if i != j:
                    somatorio += A[i, j] * x[j]

            # Aplica a fórmula de Jacobi para isolar a incógnita x_novo[i]
            x_novo[i] = (b[i] - somatorio) / A[i, i]

        # Calcula a norma infinito da diferença entre o vetor novo e o anterior para o critério de parada
        norma_numerador = np.max(np.abs(x_novo - x))
        # Calcula a norma infinito do vetor novo para servir como denominador do erro relativo
        norma_denominador = np.max(np.abs(x_novo))

        # Evita divisão por zero caso a norma do denominador seja nula
        if norma_denominador == 0:
            norma_denominador = 1.0

        # Calcula o erro relativo desta iteração
        erro_relativo = norma_numerador / norma_denominador

        # Verifica se o erro obtido é menor ou igual à tolerância estipulada
        if erro_relativo <= tol:
            # Retorna o vetor solução e o número real de iterações executadas
            return x_novo, k + 1

        # Atualiza o vetor de aproximação antigo com os novos valores obtidos para a próxima iteração
        x = x_novo.copy()

    # Retorna a última aproximação calculada caso atinja o número máximo de iterações
    return x, max_iter


# Função para o método de Gauss-Siedel
def metodo_gauss_seidel(A, b, x0, tol=1e-5, max_iter=100):
    # Identifica o número de equações e variáveis do sistema
    n = len(b)

    # Cria uma cópia inicial do vetor de aproximação que sofrerá atualizações imediatas
    x = x0.copy()

    # Inicia o laço de iterações do método computacional
    for k in range(max_iter):
        # Guarda uma cópia do vetor da iteração anterior para o cálculo do critério de parada posterior
        x_anterior = x.copy()

        # Percorre linha por linha da matriz do sistema
        for i in range(n):
            # Inicializa o acumulador para o somatório dos termos conhecidos
            somatorio = 0.0

            # Percorre todas as colunas da linha atual para calcular o somatório
            for j in range(n):
                # Ignora o elemento da diagonal principal (i == j) no somatório
                if i != j:
                    # Utiliza x[j], que já contém valores atualizados nesta mesma iteração para j < i
                    somatorio += A[i, j] * x[j]

            # Isola a incógnita atualizando imediatamente a posição i do vetor x
            x[i] = (b[i] - somatorio) / A[i, i]

        # Calcula a norma infinito da diferença entre o vetor atualizado e o da iteração anterior
        norma_numerador = np.max(np.abs(x - x_anterior))
        # Calcula a norma infinito do vetor atualizado para o denominador do erro relativo
        norma_denominador = np.max(np.abs(x))

        # Evita divisão por zero caso a norma do denominador seja nula
        if norma_denominador == 0:
            norma_denominador = 1.0

        # Calcula o erro relativo desta iteração
        erro_relativo = norma_numerador / norma_denominador

        # Verifica se o erro obtido satisfaz a tolerância definida pelo usuário
        if erro_relativo <= tol:
            # Retorna o vetor solução atualizado e o número real de iterações executadas
            return x, k + 1

    # Retorna a última aproximação calculada caso atinja o número máximo de iterações
    return x, max_iter

def calcular_norma_um_matriz(A):
    # Identifica o número de linhas e colunas da matriz A
    linhas, colunas = A.shape

    # Inicializa a variável para armazenar o maior somatório entre as colunas
    max_soma = 0.0

    # Percorre coluna por coluna da matriz para realizar o somatório vertical
    for j in range(colunas):
        # Inicializa o acumulador para a soma dos valores absolutos da coluna atual
        soma_coluna = 0.0

        # Percorre todas as linhas da coluna atual
        for i in range(linhas):
            # Acumula o valor absoluto do elemento atual da matriz
            soma_coluna += np.abs(A[i, j])

        # Verifica se a soma da coluna atual é maior que o máximo registrado anteriormente
        if soma_coluna > max_soma:
            # Atualiza o valor máximo com a maior soma absoluta encontrada
            max_soma = soma_coluna

    # Retorna o resultado final correspondente à Norma 1 da matriz
    return max_soma


def calcular_norma_infinito_matriz(A):
    # Identifica o número de linhas e colunas da matriz A
    linhas, colunas = A.shape

    # Inicializa a variável para armazenar o maior somatório entre as linhas
    max_soma = 0.0

    # Percorre linha por linha da matriz para realizar o somatório horizontal
    for i in range(linhas):
        # Inicializa o acumulador para a soma dos valores absolutos da linha atual
        soma_linha = 0.0

        # Percorre todas as colunas da linha atual
        for j in range(colunas):
            # Acumula o valor absoluto do elemento atual da matriz
            soma_linha += np.abs(A[i, j])

        # Verifica se a soma da linha atual é maior que o máximo registrado anteriormente
        if soma_linha > max_soma:
            # Atualiza o valor máximo com a maior soma absoluta encontrada
            max_soma = soma_linha

    # Retorna o resultado final correspondente à Norma Infinito da matriz
    return max_soma


def calcular_norma_frobenius_matriz(A):
    # Identifica o número de linhas e colunas da matriz A
    linhas, colunas = A.shape

    # Inicializa o acumulador para a soma dos quadrados de todos os elementos
    soma_quadrados = 0.0

    # Percorre cada linha da matriz no espaço bidimensional
    for i in range(linhas):
        # Percorre cada coluna da linha correspondente
        for j in range(colunas):
            # Acumula o quadrado do elemento atual na variável de controle
            soma_quadrados += A[i, j] ** 2

    # Aplica a raiz quadrada sobre o somatório total dos elementos ao quadrado
    norma_frob = np.sqrt(soma_quadrados)

    # Retorna o resultado final correspondente à Norma de Frobenius da matriz
    return norma_frob


def calcular_norma_um_vetor(b):
    # Identifica o tamanho (número de elementos) do vetor b
    n = len(b)

    # Inicializa o acumulador para a soma dos valores absolutos
    soma_absoluta = 0.0

    # Percorre cada elemento do vetor unidimensional
    for i in range(n):
        # Acumula o valor absoluto do elemento atual do vetor
        soma_absoluta += np.abs(b[i])

    # Retorna o resultado final correspondente à Norma 1 do vetor
    return soma_absoluta


def calcular_norma_infinito_vetor(b):
    # Identifica o tamanho (número de elementos) do vetor b
    n = len(b)

    # Inicializa a variável para registrar o maior valor absoluto encontrado
    max_valor = 0.0

    # Percorre cada elemento do vetor para fazer a comparação linear
    for i in range(n):
        # Obtém o valor absoluto do elemento atual
        valor_atual = np.abs(b[i])

        # Verifica se o valor absoluto atual é maior que o máximo registrado
        if valor_atual > max_valor:
            # Atualiza o limite máximo com o maior valor absoluto encontrado
            max_valor = valor_atual

    # Retorna o resultado correspondente à Norma Infinito do vetor
    return max_valor


def calcular_norma_p_vetor(b, p):
    # Identifica o tamanho (número de elementos) do vetor b
    n = len(b)

    # Inicializa o acumulador para a soma das potências dos elementos
    soma_potencias = 0.0

    # Percorre cada elemento do vetor unidimensional
    for i in range(n):
        # Acumula o valor absoluto do elemento elevado à potência p
        soma_potencias += np.abs(b[i]) ** p

    # Aplica a raiz de ordem p sobre o somatório total das potências
    norma_p = soma_potencias ** (1.0 / p)

    # Retorna o resultado final correspondente à Norma p do vetor
    return norma_p


def calcular_norma_induzida_vetor(b, M):
    # Identifica o tamanho (número de elementos) do vetor b
    n = len(b)

    # Inicializa o acumulador para o produto quadrático interno bilinear (b^T * M * b)
    termo_bilinear = 0.0

    # Percorre as linhas da matriz de indução positiva definida
    for i in range(n):
        # Percorre as colunas da matriz de indução positiva definida
        for j in range(n):
            # Acumula o produto combinado dos elementos dos vetores e da matriz M[i, j]
            termo_bilinear += b[i] * M[i, j] * b[j]

    # Prevenção contra valores levemente negativos decorrentes de precisão numérica
    if termo_bilinear < 0:
        return np.sqrt(np.abs(termo_bilinear))

    # Aplica a raiz quadrada sobre o resultado do produto bilinear interno
    norma_induzida = np.sqrt(termo_bilinear)

    # Retorna o resultado final correspondente à Norma Induzida pela matriz
    return norma_induzida


def inverter_matriz_lu(L, U):
    # Identifica a dimensão da matriz quadrada baseada nas linhas de L
    n = L.shape[0]

    # Aloca na memória uma matriz identidade que servirá como os vetores b do sistema
    I = np.eye(n, dtype=float)
    # Aloca na memória uma matriz vazia para armazenar as colunas da matriz inversa
    A_inv = np.zeros((n, n), dtype=float)

    # Percorre cada coluna da matriz identidade para resolver o sistema correspondente
    for j in range(n):
        # Extrai a coluna j atual como o vetor b do sistema linear
        b_coluna = I[:, j]

        # Resolve Ly = b através do método de substituição para frente
        y = substituicao_para_frente(L, b_coluna)
        # Resolve Ux = y através do método de substituição para trás
        x = substituicao_para_tras(U, y)

        # Armazena o vetor solução x obtido na coluna correspondente da matriz inversa
        A_inv[:, j] = x

    # Retorna a matriz inversa completamente calculada
    return A_inv


def calcular_numero_condicao(A, L, U):
    # Computa a matriz inversa utilizando as matrizes fatoradas L e U
    A_inv = inverter_matriz_lu(L, U)

    # Calcula a Norma 1 da matriz original A utilizando a função criada anteriormente
    norma_A = calcular_norma_um_matriz(A)
    # Computa a Norma 1 da matriz inversa calculada
    norma_A_inv = calcular_norma_um_matriz(A_inv)

    # O número de condição exato é o produto das normas de A e de sua inversa
    cond_A = norma_A * norma_A_inv

    # Retorna o valor real correspondente ao número de condição exato
    return cond_A


def estimar_numero_condicao(A, L, U, max_iter_est=5):
    # Identifica a dimensão da matriz quadrada baseada nas linhas de A
    n = A.shape[0]

    # Aloca na memória um vetor de teste inicial preenchido uniformemente por 1/n
    v = np.ones(n, dtype=float) / n
    # Calcula a Norma 1 da matriz original A utilizando a função criada anteriormente
    norma_A = calcular_norma_um_matriz(A)

    # Inicializa a variável para acumular a estimativa da norma da inversa
    estimativa_norma_inv = 0.0

    # Inicia o laço iterativo para refinar a estimativa do vetor de maior crescimento
    for _ in range(max_iter_est):
        # Resolve A * w = v resolvendo sucessivamente Ly = v e Uw = y
        y = substituicao_para_frente(L, v)
        w = substituicao_para_tras(U, y)

        # Computa a Norma 1 do vetor resultante w
        norma_w = calcular_norma_um_vetor(w)

        # Se a norma obtida for menor ou igual à anterior, encerra o laço
        if norma_w <= estimativa_norma_inv:
            break

        # Atualiza a melhor estimativa da norma da inversa encontrada até o momento
        estimativa_norma_inv = norma_w

        # Evita divisão por zero ao normalizar o vetor se a norma for nula
        if norma_w == 0:
            break

        # Atualiza o vetor de teste v com o sinal dos componentes de w para a próxima iteração
        v = np.sign(w) / n

    # A estimativa do número de condição é o produto da norma de A pela estimativa da norma da inversa
    cond_est = norma_A * estimativa_norma_inv

    # Retorna o valor real aproximado correspondente à estimativa do número de condição
    return cond_est


def calcular_produto_interno_vetores(v1, v2):
    # Identifica o tamanho do primeiro vetor (assumindo que ambos possuem a mesma dimensão)
    n = len(v1)

    # Inicializa o acumulador para a soma dos produtos termo a termo
    resultado_escalar = 0.0

    # Percorre cada posição dos vetores de forma sincronizada
    for i in range(n):
        # Multiplica os componentes correspondentes de cada vetor e acumula no resultado
        resultado_escalar += v1[i] * v2[i]

    # Retorna o valor real escalar resultante do produto interno <v1, v2>
    return resultado_escalar


def calcular_distancia_vetores(v1, v2):
    # Identifica o tamanho do primeiro vetor para controle do laço
    n = len(v1)

    # Inicializa o acumulador para a soma dos quadrados das diferenças
    soma_quadrados_dif = 0.0

    # Percorre os vetores elemento por elemento para encontrar a diferença espacial
    for i in range(n):
        # Calcula a diferença entre os componentes na posição i e eleva ao quadrado
        soma_quadrados_dif += (v1[i] - v2[i]) ** 2

    # Aplica a raiz quadrada sobre o somatório dos quadrados das diferenças (distância Euclidiana)
    distancia = np.sqrt(soma_quadrados_dif)

    # Retorna o valor real correspondente à distância geométrica entre os dois vetores
    return distancia


def calcular_distancia_matrizes(Matriz1, Matriz2):
    # Identifica o número de linhas e colunas (assumindo que ambas possuem a mesma dimensão)
    linhas, colunas = Matriz1.shape

    # Inicializa o acumulador para a soma dos quadrados das diferenças elemento a elemento
    soma_quadrados_dif = 0.0

    # Percorre cada linha das matrizes no espaço bidimensional
    for i in range(linhas):
        # Percorre cada coluna da linha correspondente
        for j in range(colunas):
            # Calcula a diferença entre os elementos homólogos e eleva ao quadrado
            soma_quadrados_dif += (Matriz1[i, j] - Matriz2[i, j]) ** 2

    # Aplica a raiz quadrada sobre o somatório total obtido (Distância de Frobenius)
    distancia_matricial = np.sqrt(soma_quadrados_dif)

    # Retorna o valor real escalar correspondente à distância geométrica entre as duas matrizes
    return distancia_matricial


def fatoracao_qr(A):
    # Identifica o número de linhas e colunas da matriz A
    linhas, colunas = A.shape

    # Aloca na memória a matriz Q com as mesmas dimensões de A, preenchida por zeros
    Q = np.zeros((linhas, colunas), dtype=float)
    # Aloca na memória a matriz quadrada R (colunas x colunas) preenchida por zeros
    R = np.zeros((colunas, colunas), dtype=float)

    # Cria uma cópia de trabalho da matriz A para aplicar as projeções ortogonais
    V = A.copy().astype(float)

    # Percorre cada coluna da matriz para construir a base ortonormal
    for j in range(colunas):
        # Inicializa o acumulador para calcular a norma Euclidiana da coluna atual de V
        soma_quadrados = 0.0
        for i in range(linhas):
            soma_quadrados += V[i, j] ** 2

        # Define o elemento da diagonal principal de R como a norma da coluna j
        R[j, j] = np.sqrt(soma_quadrados)

        # Se a norma for diferente de zero, normaliza a coluna para obter o vetor de Q
        if R[j, j] != 0:
            Q[:, j] = V[:, j] / R[j, j]
        else:
            Q[:, j] = 0.0

        # Percorre as colunas restantes à direita para ortogonalizá-las em relação a Q[:, j]
        for k in range(j + 1, colunas):
            # Inicializa o acumulador para o produto interno entre Q[:, j] e V[:, k]
            produto_interno = 0.0
            for i in range(linhas):
                produto_interno += Q[i, j] * V[i, k]

            # Armazena o coeficiente de projeção na matriz superior R
            R[j, k] = produto_interno

            # Subtrai a projeção linear da coluna V[:, k] para torná-la ortogonal
            V[:, k] = V[:, k] - R[j, k] * Q[:, j]

    # Retorna as matrizes Q (ortogonal) e R (triangular superior) resultantes
    return Q, R


# =====================================================================
# CÓDIGO PRINCIPAL - IMPLEMENTAÇÃO DOS MÉTODOS MATRICIAIS E ITERATIVOS
# =====================================================================

usar_dados_simulados = False

while True:
    print("ENTRADA DE DADOS - SISTEMAS LINEARES")
    print("-" * 40)
    print("[1] Fazer Upload de uma planilha do Excel (.xlsx)")
    print("[2] Usar dados simulados de teste automático (Sem precisar de arquivo)")
    print("-" * 40)

    opcao = input("Digite a opção desejada (1 ou 2): ").strip()

    if opcao == '1':
        try:
            print("\nPor favor, faça o upload do seu arquivo Excel (.xlsx): ")
            arquivos_carregados = files.upload()

            if not arquivos_carregados:
                print("\n[AVISO] Upload cancelado! Retornando ao menu...\n")
                continue

            nome_do_arquivo = list(arquivos_carregados.keys())[0]
            print(f"Arquivo '{nome_do_arquivo}' carregado com sucesso!\n")
            dados_sistema = pd.read_excel(nome_do_arquivo)
            break

        except Exception as e:
            print(f"\n[ERRO] Falha ao processar o arquivo: {str(e)}")
            print("Tente novamente ou mude de opção.\n")
            continue

    elif opcao == '2':
        usar_dados_simulados = True
        break
    else:
        print("\n[OPÇÃO INVÁLIDA] Por favor, digite apenas 1 ou 2.\n")

# Se o usuário optou pelos dados simulados, constrói o DataFrame compatível
if usar_dados_simulados:
    print("\nCarregando dados de teste automáticos de Álgebra Linear...\n")

    # Criando um sistema 3x3 bem condicionado e diagonalmente dominante para garantir convergência
    dados_simulados = {
        'A_col1': [10.0, 1.0, 2.0],
        'A_col2': [-1.0, 11.0, -1.0],
        'A_col3': [2.0, -1.0, 10.0],
        'b': [6.0, 25.0, -11.0],
        'P_col1': [1.0, 0.0, 0.0],
        'P_col2': [0.0, 1.0, 0.0],
        'P_col3': [0.0, 0.0, 1.0],
        'c': [1.0, 1.0, 1.0],
        'x0': [0.0, 0.0, 0.0],
        'tolerancia': [1e-5, np.nan, np.nan],  # Alinha o tamanho do array com NaN
        'max_iter': [100, np.nan, np.nan]
    }
    dados_sistema = pd.DataFrame(dados_simulados)


# Em vez de listar coluna por coluna, filtramos dinamicamente pelo prefixo
A = dados_sistema.filter(like='A_col').to_numpy()
b = dados_sistema['b'].to_numpy()

P = dados_sistema.filter(like='P_col').to_numpy()
c = dados_sistema['c'].to_numpy()

# ---------------------------------------------------------------------
# INTERRUPÇÃO DE SEGURANÇA E DISPARO DE MENSAGENS DE ERRO CRÍTICAS
# ---------------------------------------------------------------------
try:
    validar_dados_sistema(A, b, P, c)
except ValueError as erro_detectado:
    print("\n" + "!"*60)
    print(erro_detectado)
    print("!"*60 + "\n")
    raise SystemExit("Execução interrompida com segurança para evitar quebras abruptas no código.")

print("Matriz A extraída:\n", A)
print("\nVetor b extraído:", b)
print("\nMatriz P extraída:\n", P)
print("\nVetor c extraído:", c)
print("-" * 50)

"""
Verificação e tratamento de flexibilidade para os parâmetros dos métodos iterativos.
Caso 'x0', 'tolerancia' ou 'max_iter' não estejam na planilha, adotamos hipóteses padrões estáveis.
"""
# Tratamento para o vetor de aproximação inicial x0
if 'x0' in dados_sistema.columns:
    x0 = dados_sistema['x0'].to_numpy()
    # Remove valores NaN caso venham da planilha por desalinhamento de tamanho
    x0 = x0[~np.isnan(x0)]
    if len(x0) == 0:
        x0 = np.zeros(len(b), dtype=float)
else:
    # Se ausente, inicializa na memória um vetor de zeros com a mesma dimensão de b
    x0 = np.zeros(len(b), dtype=float)

# Tratamento para a tolerância e o limite máximo de iterações do laço computacional
tolerancia = dados_sistema['tolerancia'].iloc[0] if 'tolerancia' in dados_sistema.columns and not pd.isna(dados_sistema['tolerancia'].iloc[0]) else 1e-5
max_iteracoes = int(dados_sistema['max_iter'].iloc[0]) if 'max_iter' in dados_sistema.columns and not pd.isna(dados_sistema['max_iter'].iloc[0]) else 100

print(f"Configurações adotadas -> Tolerância: {tolerancia} | Máx. Iterações: {max_iteracoes}")
print(f"Vetor inicial x0 utilizado:\n {x0}")
print("-" * 50)

"""
Fatoração LU real aplicada sobre a matriz A do sistema.
Aqui, entramos na resolução da LETRA b) da Questão 1.
"""
L_calculado, U_calculado = fatoracao_lu(A)

"""
Aplicação dos métodos de substituição nas matrizes fatoradas em L e U.
Aqui, entramos na resolução da LETRA a) da Questão 1.
"""
resultado_frente = substituicao_para_frente(L_calculado, b)
resultado_tras   = substituicao_para_tras(U_calculado, b)


"""
Aplicação dos métodos iterativos de resolução de sistemas lineares.
Aqui, entramos na resolução da LETRA c) da Questão 1.
"""
resultado_jacobi, iter_jacobi = metodo_jacobi(A, b, x0, tol=tolerancia, max_iter=max_iteracoes)
resultado_seidel, iter_seidel = metodo_gauss_seidel(A, b, x0, tol=tolerancia, max_iter=max_iteracoes)


print("\nResultado da Substituição para Frente:")
print(resultado_frente)

print("\nResultado da Substituição para Trás:")
print(resultado_tras)

print(f"\nResultado do Método de Jacobi (Convergido em {iter_jacobi} iterações):")
print(resultado_jacobi)

print(f"\nResultado do Método de Gauss-Seidel (Convergido em {iter_seidel} iterações):")
print(resultado_seidel)


"""
Cálculo e exibição de todas as normas matriciais da matriz A lida do Excel.
Aqui, entramos na resolução da LETRA d) da Questão 1.
"""
norma_1_A = calcular_norma_um_matriz(A)
norma_inf_A = calcular_norma_infinito_matriz(A)
norma_frob_A = calcular_norma_frobenius_matriz(A)


print("\n" + "="*20 + " NORMAS MATRICIAIS DA MATRIZ A " + "="*20)
print(f"Norma 1 (Máxima soma absoluta das colunas): {norma_1_A:.4f}")
print(f"Norma Infinito (Máxima soma absoluta das linhas): {norma_inf_A:.4f}")
print(f"Norma de Frobenius (Raiz da soma dos quadrados): {norma_frob_A:.4f}")
print("="*71)


"""
Cálculo e exibição de todas as normas vetoriais do vetor b lido do Excel.
Aqui, entramos na resolução da LETRA e) da Questão 1.
Para a norma induzida, utilizaremos a própria matriz A como a matriz positiva definida.
"""

# Define o parâmetro de ordem p para o cálculo da norma p (exemplo: p = 3)
p_escolhido = 3
norma_1_b = calcular_norma_um_vetor(b)
norma_inf_b = calcular_norma_infinito_vetor(b)
norma_p_b = calcular_norma_p_vetor(b, p=p_escolhido)
norma_ind_b = calcular_norma_induzida_vetor(b, A)


print("\n" + "="*20 + " NORMAS VETORIAIS DO VETOR b " + "="*20)
print(f"Norma 1 (Soma dos valores absolutos): {norma_1_b:.4f}")
print(f"Norma Infinito (Maior valor absoluto encontrado): {norma_inf_b:.4f}")
print(f"Norma p (Com p = {p_escolhido}): {norma_p_b:.4f}")
print(f"Norma Induzida (Utilizando a matriz A do sistema): {norma_ind_b:.4f}")
print("="*69)

"""
Cálculo do número de condição exato e de uma estimativa computacional econômica.
Aqui, entramos na resolução da LETRA f) da Questão 1.
Utiliza as matrizes L_calculado e U_calculado obtidas na fatoração anterior.
"""
num_condicao_exato = calcular_numero_condicao(A, L_calculado, U_calculado)
num_condicao_estimado = estimar_numero_condicao(A, L_calculado, U_calculado)


print("\n" + "="*20 + " ANÁLISE DE CONDICIONAMENTO DA MATRIZ A " + "="*20)
print(f"Número de Condição Exato K(A) (Norma 1): {num_condicao_exato:.4f}")
print(f"Estimativa do Número de Condição K(A):    {num_condicao_estimado:.4f}")

# Bloco condicional para interpretação do resultado no relatório/vídeo
if num_condicao_exato > 1000:
    print("Avaliação Diagnóstica: A matriz A é MAL CONDICIONADA. Pequenas perturbações em b podem causar grandes erros em x.")
else:
    print("Avaliação Diagnóstica: A matriz A é BEM CONDICIONADA. O sistema apresenta boa estabilidade numérica.")
print("="*80)

"""
Cálculo do produto interno e da distância Euclidiana entre os vetores b e c.
Aqui, entramos na resolução da LETRA g) da Questão 1.
Os vetores b e c foram previamente extraídos da planilha do Excel.
"""
produto_interno_bc = calcular_produto_interno_vetores(b, c)
distancia_bc = calcular_distancia_vetores(b, c)

print("\n" + "="*20 + " ANÁLISE GEOMÉTRICA DOS VETORES B E C " + "="*20)
print(f"Produto Interno <b, c>:                  {produto_interno_bc:.4f}")
print(f"Distância Euclidiana entre b e c:       {distancia_bc:.4f}")
print("="*78)

"""
Cálculo e exibição da distância espacial de Frobenius entre as matrizes A e P.
Aqui, entramos na resolução da LETRA h) da Questão 1.
As matrizes A e P foram previamente extraídos e convertidas a partir do Excel.
"""
distancia_AP = calcular_distancia_matrizes(A, P)

print("\n" + "="*20 + " ANÁLISE GEOMÉTRICA DAS MATRIZES A E P " + "="*20)
print(f"Distância Matricial (Frobenius) entre A e P: {distancia_AP:.4f}")
print("="*79)


"""
Decomposição da matriz A nas matrizes ortogonal Q e triangular superior R.
Aqui, entramos na resolução da LETRA i) da Questão 1.
A matriz A foi previamente extraída e convertidas a partir do Excel.
"""
Q_resultado, R_resultado = fatoracao_qr(A)

print("\n" + "="*20 + " FATORAÇÃO QR DA MATRIZ A " + "="*20)
print("Matriz Ortogonal Q obtida:\n", Q_resultado)
print("\nMatriz Triangular Superior R obtida:\n", R_resultado)

# Teste de validação interna da fatoração para o relatório/vídeo
A_reconstruida = np.zeros(A.shape, dtype=float)
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        for k in range(R_resultado.shape[0]):
            A_reconstruida[i, j] += Q_resultado[i, k] * R_resultado[k, j]

print("\n" + "-"*30 + " VALIDAÇÃO " + "-"*30)
print("Matriz Reconstruída (Q * R):\n", A_reconstruida)
print("="*66)


ENTRADA DE DADOS - SISTEMAS LINEARES
----------------------------------------
[1] Fazer Upload de uma planilha do Excel (.xlsx)
[2] Usar dados simulados de teste automático (Sem precisar de arquivo)
----------------------------------------
Digite a opção desejada (1 ou 2): 1

Por favor, faça o upload do seu arquivo Excel (.xlsx): 


Saving matrizes3x3-questao1-compativel (1).xlsx to matrizes3x3-questao1-compativel (1) (3).xlsx
Arquivo 'matrizes3x3-questao1-compativel (1) (3).xlsx' carregado com sucesso!

[VALIDAÇÃO] Sucesso: Matrizes e vetores possuem dimensões válidas e alinhadas.
[VALIDAÇÃO] A matriz A é estritamente diagonal dominante (Convergência garantida).
Matriz A extraída:
 [[10. -1.  2.]
 [ 1. 11. -1.]
 [ 2. -1. 10.]]

Vetor b extraído: [  6.  25. -11.]

Matriz P extraída:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Vetor c extraído: [1. 1. 1.]
--------------------------------------------------
Configurações adotadas -> Tolerância: 1.0 | Máx. Iterações: 100
Vetor inicial x0 utilizado:
 [0. 0. 0.]
--------------------------------------------------

Resultado da Substituição para Frente:
[  6.          24.4        -10.44144144]

Resultado da Substituição para Trás:
[ 1.04397523  2.12725225 -1.15625   ]

Resultado do Método de Jacobi (Convergido em 1 iterações):
[ 0.6         2.27272727 -1.1       ]

Resultado d

In [ ]:
#Código da questão 2


import io
import random
import numpy as np
import pandas as pd
from google.colab import files

def e_valido_sudoku(tabuleiro, linha, coluna, numero):
    """
    Verifica se a inserção de um número no tabuleiro viola as regras do Sudoku.
    """
    # Verifica se o número já existe na linha correspondente
    for j in range(9):
        if tabuleiro[linha, j] == numero:
            return False

    # Verifica se o número já existe na coluna correspondente
    for i in range(9):
        if tabuleiro[i, coluna] == numero:
            return False

    # Identifica a linha e a coluna iniciais do bloco 3x3 atual
    inicio_linha = (linha // 3) * 3
    inicio_coluna = (coluna // 3) * 3

    # Percorre as células internas do subbloco 3x3 correspondente
    for i in range(3):
        for j in range(3):
            if tabuleiro[inicio_linha + i, inicio_coluna + j] == numero:
                return False

    return True


def resolver_sudoku(tabuleiro):
    """
    Algoritmo de força bruta com backtracking para preenchimento ou resolução da matriz.
    """
    for i in range(9):
        for j in range(9):
            if tabuleiro[i, j] == 0:
                numeros = list(range(1, 10))
                random.shuffle(numeros)

                for numero in numeros:
                    if e_valido_sudoku(tabuleiro, i, j, numero):
                        tabuleiro[i, j] = numero

                        if resolver_sudoku(tabuleiro):
                            return True

                        # Desfaz a atribuição (backtracking)
                        tabuleiro[i, j] = 0

                return False
    return True


def exibir_tabuleiro_sudoku(tabuleiro):
    """
    Exibição visual e estilizada das matrizes de Sudoku no console.
    """
    for i in range(9):
        if i % 3 == 0 and i != 0:
            print("-" * 25)

        linha_texto = ""
        for j in range(9):
            if j % 3 == 0 and j != 0:
                linha_texto += "| "

            if tabuleiro[i, j] == 0:
                linha_texto += ". "
            else:
                linha_texto += str(tabuleiro[i, j]) + " "

        print(linha_texto)


# =====================================================================
# CÓDIGO PRINCIPAL - EXECUÇÃO COM MENU REPETITIVO
# =====================================================================

print("="*60)
print("SUDOKU COMPUTACIONAL - MENU INTERATIVO")
print("="*60)

jogo_desafio = None
usar_dados_simulados = False

while True:
    print("\nENTRADA DE DADOS")
    print("-" * 10)
    print("[1] Fazer Upload de um tabuleiro do Excel (.xlsx)")
    print("[2] Usar matriz simulada de teste automático (Sem precisar de arquivo)")
    print("-" * 10)

    opcao = input("Digite a opção desejada (1 ou 2): ").strip()

    if opcao == '1':
        try:
            print("\nPor favor, envie o arquivo Excel (.xls ou .xlsx) contendo a matriz 9x9:")
            arquivos_carregados = files.upload()

            if not arquivos_carregados:
                print("\n[AVISO] Upload cancelado! Retornando ao menu...\n")
                continue

            nome_arquivo = list(arquivos_carregados.keys())[0]
            conteudo_arquivo = arquivos_carregados[nome_arquivo]

            # Leitura do Excel via Pandas (sem cabeçalho)
            df = pd.read_excel(io.BytesIO(conteudo_arquivo), header=None)

            # Validação de Dimensão: Deve ser exatamente 9x9
            if df.shape != (9, 9):
                print(f"\n[ERRO] Formato inválido! O arquivo contém dimensões {df.shape}, mas deve ser 9x9.\n")
                continue

            # Converte para array NumPy de inteiros
            matriz_np = df.to_numpy(dtype=int)

            # Validação de Conteúdo: Apenas valores entre 0 e 9
            if not np.all((matriz_np >= 0) & (matriz_np <= 9)):
                print("\n[ERRO] O tabuleiro contém valores inválidos! Use apenas números de 0 a 9.\n")
                continue

            print(f"\nArquivo '{nome_arquivo}' carregado e validado com sucesso!")
            jogo_desafio = matriz_np
            break

        except Exception as e:
            print(f"\n[ERRO] Falha crítica ao processar o arquivo: {e}. Tente novamente.\n")
            continue

    elif opcao == '2':
        usar_dados_simulados = True
        break
    else:
        print("\n[OPÇÃO INVÁLIDA] Por favor, digite apenas 1 ou 2.\n")

# Se o usuário escolheu a opção 2, gera uma nova matriz com o mínimo de pistas (17 números)
if usar_dados_simulados:
    print("\nCarregando matriz de teste automática (Diferente)...\n")
    # Nova matriz desafiadora (0 representa espaços vazios)
    jogo_desafio = np.array([
        [0, 0, 0, 0, 0, 0, 0, 1, 2],
        [0, 0, 0, 0, 0, 0, 0, 0, 3],
        [0, 0, 2, 3, 0, 0, 4, 0, 0],
        [0, 0, 1, 8, 0, 0, 0, 0, 5],
        [0, 6, 0, 0, 7, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 9, 0, 0, 0],
        [0, 0, 0, 5, 0, 0, 6, 0, 0],
        [7, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 8, 0, 0, 2, 0, 0, 0]
    ], dtype=int)


# Executa a resolução do jogo caso tenhamos uma matriz válida
if jogo_desafio is not None:
    print("\n" + "="*20 + " TABULEIRO DO JOGO (ENTRADA SOLICITADA) " + "="*20)
    exibir_tabuleiro_sudoku(jogo_desafio)
    print("="*79)

    # Clona a matriz de entrada para calcular a resposta
    gabarito_solucao = jogo_desafio.copy()

    print("\nProcessando a solução via algoritmo de Backtracking...")

    # Executa o solver matemático
    if resolver_sudoku(gabarito_solucao):
        print("\n" + "="*20 + " GABARITO / RESPOSTA ENCONTRADA " + "="*20)
        print("Validação matemática das restrições por linhas, colunas e quadrantes 3x3:\n")
        exibir_tabuleiro_sudoku(gabarito_solucao)
        print("="*78)
    else:
        print("\n Atenção: Este tabuleiro de Sudoku fornecido NÃO possui uma solução matemática válida!")
        print("Verifique se os números iniciais não violam as regras básicas de colisão do jogo.")


SUDOKU COMPUTACIONAL - MENU INTERATIVO

ENTRADA DE DADOS
----------
[1] Fazer Upload de um tabuleiro do Excel (.xlsx)
[2] Usar matriz simulada de teste automático (Sem precisar de arquivo)
----------
Digite a opção desejada (1 ou 2): 1

Por favor, envie o arquivo Excel (.xls ou .xlsx) contendo a matriz 9x9:


Saving matriz9x9-compativel-sudoku.xlsx to matriz9x9-compativel-sudoku (2).xlsx

Arquivo 'matriz9x9-compativel-sudoku (2).xlsx' carregado e validado com sucesso!

==================== TABULEIRO DO JOGO (ENTRADA SOLICITADA) ====================
5 3 . | . 7 . | . . . 
6 . . | 1 9 5 | . . . 
. 9 8 | . . . | . 6 . 
-------------------------
8 . . | . 6 . | . . 3 
4 . . | 8 . 3 | . . 1 
7 . . | . 2 . | . . 6 
-------------------------
. 6 . | . . . | 2 8 . 
. . . | 4 1 9 | . . 5 
. . . | . 8 . | . 7 9 

Processando a solução via algoritmo de Backtracking...

==================== GABARITO / RESPOSTA ENCONTRADA ====================
Validação matemática das restrições por linhas, colunas e quadrantes 3x3:

5 3 4 | 6 7 8 | 9 1 2 
6 7 2 | 1 9 5 | 3 4 8 
1 9 8 | 3 4 2 | 5 6 7 
-------------------------
8 5 9 | 7 6 1 | 4 2 3 
4 2 6 | 8 5 3 | 7 9 1 
7 1 3 | 9 2 4 | 8 5 6 
-------------------------
9 6 1 | 5 3 7 | 2 8 4 
2 8 7 | 4 1 9 | 6 3 5 
3 4 5 | 2 8 6 | 1 7 9 


In [1]:
# Questão 3




import pandas as pd      # Para trabalhar com dados de entradas salvo nas planilhas. Cada função utilizada será no formato um pd.funcao()
import numpy as np       # Para trabalhar com a manipulação de dados numéricos. Cada função será no formato np.funcao()
from google.colab import files  # Biblioteca do Colab para fazer upload de arquivos

# Funções para calcular as distâncias (Normas)

def distancia_norma_1(x1, x2):
    # Norma L1 - Distância de Manhattan
    return np.sum(np.abs(x1 - x2))

def distancia_norma_2(x1, x2):
    # Norma L2 - Distância Euclidiana
    return np.sqrt(np.sum((x1 - x2) ** 2))

def distancia_norma_infinito(x1, x2):
    # Norma Infinito - Distância de Chebyshev
    return np.max(np.abs(x1 - x2))


# Algoritmo KNN

def classificador_knn(X_treino, y_treino, instancia_teste, k=3, norma='l2'):
    distancias = []

    # Passa por cada linha do treino para calcular a distância até o ponto de teste
    for i in range(len(X_treino)):
        if norma == 'l1':
            d = distancia_norma_1(instancia_teste, X_treino[i])

        elif norma == 'inf':  # norma infinito
            d = distancia_norma_infinito(instancia_teste, X_treino[i])

        else:  # padrao: L2 (Euclidiana)
            d = distancia_norma_2(instancia_teste, X_treino[i])

        # Guarda a distância junto com a classe daquele ponto
        distancias.append((d, y_treino[i]))

    # Ordena as distâncias da menor para a maior
    distancias.sort(key=lambda x: x[0])

    # Pega os k vizinhos mais próximos
    vizinhos = distancias[:k]

    # Conta quantos votos cada classe recebeu
    votos = {}
    for vizinho in vizinhos:
        rotulo = vizinho[1]
        votos[rotulo] = votos.get(rotulo, 0) + 1

    # Vê qual classe teve mais votos e retorna
    rotulo_predito = max(votos, key=votos.get)
    return rotulo_predito


# Execução do Código com Menu Repetitivo

usar_dados_simulados = False

while True:

    print("ENTRADA DE DADOS")
    print("-" * 10)
    print("[1] Fazer Upload de uma planilha do Excel (.xlsx)")
    print("[2] Usar dados simulados de teste automático (Sem precisar de arquivo)")
    print("-" * 10)

    opcao = input("Digite a opção desejada (1 ou 2): ").strip()

    if opcao == '1':
        try:
            print("\nPor favor, faça o upload do seu arquivo Excel (.xlsx): ")
            arquivos_carregados = files.upload()

            # Se a lista de arquivos estiver vazia, significa que o usuário cancelou a janela
            if not arquivos_carregados:
                print("\n[AVISO] Upload cancelado! Retornando ao menu...\n")
                continue

            nome_do_arquivo = list(arquivos_carregados.keys())[0]
            print(f"Arquivo '{nome_do_arquivo}' carregado com sucesso!\n")
            # skiprows=3 pula as 3 primeiras linhas decorativa
            # header=None avisa que a leitura começará diretamente pelos dados
            df_knn = pd.read_excel(nome_do_arquivo, skiprows=3, header=None)

            if df_knn.empty:
              print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
              print("[ERRO DE DADOS] A planilha está vazia.")
              print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
              exit()

            break

        except Exception as e:
            print("\n[ERRO] Falha ao processar o arquivo. Tente novamente ou mude de opção.\n")
            continue

    elif opcao == '2':
        usar_dados_simulados = True
        break
    else:
        print("\n[OPÇÃO INVÁLIDA] Por favor, digite apenas 1 ou 2.\n")

# Se saiu do loop com a opção 2 ativada, gera os dados automáticos
if usar_dados_simulados:
    print("\nCarregando dados de teste automáticos...\n")
    dados_simulados = {
        'Caracteristica_1': [1.0, 1.5, 2.0, 7.0, 8.0, 9.0] #atributo X
        ,'Caracteristica_2': [1.2, 1.8, 2.1, 7.5, 8.2, 9.5] #atributo Y
        ,'Classe': [0, 0, 0, 1, 1, 1] #rotulo
    }
    df_knn = pd.DataFrame(dados_simulados)



if df_knn.shape[1] < 2:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE FORMATO]")
    print("A planilha deve possuir pelo menos:")
    print("- 1 coluna de atributos")
    print("- 1 coluna de classe")
    print(f"Dimensão encontrada: {df_knn.shape}")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()

# Separa os atributos (X) das classes (y)

X_treino = df_knn.iloc[:, :-1].to_numpy()
y_treino = df_knn.iloc[:, -1].to_numpy()

if len(X_treino) < 3:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE DADOS]")
    print("São necessários pelo menos 3 exemplos para executar o KNN com k=3.")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()

# Se a primeira linha for texto, ignore-a filtrando a partir do índice 1:

if isinstance(X_treino[0, 0], str):
    print("\n[AVISO] Cabeçalho de texto detectado na matriz de dados. Removendo linha de títulos...")
    X_treino = X_treino[1:]
    y_treino = y_treino[1:]

# Garante que o NumPy entenda a matriz como números decimais e preserva as duas dimensões (linhas, colunas)
try:
    X_treino = np.array(X_treino, dtype=float)

except ValueError:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE DADOS]")
    print("Foram encontrados valores")
    print("não numéricos nos atributos.")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()

# Agora o .shape[1] nunca mais dará undefined ou erro, pois a matriz está garantida
numero_de_colunas = X_treino.shape[1]


# --- Testes ---

# Criamos pontos de teste que se adaptam ao tamanho exato da planilha utilizada
lista_de_testes = [
    np.full(numero_de_colunas, 2.0),  # Cria um ponto preenchido com 2.0
    np.full(numero_de_colunas, 5.0),  # Cria um ponto preenchido com 5.0
    np.full(numero_de_colunas, 8.0)   # Cria um ponto preenchido com 8.0
]

k_vizinhos = 3

if k_vizinhos > len(X_treino):
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE CONFIGURAÇÃO]")
    print(f"k = {k_vizinhos}")
    print(f"Número de amostras = {len(X_treino)}")
    print("k não pode ser maior que a quantidade")
    print("de exemplos de treinamento.")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()




# Impressao dos dados de teste

# Modifica temporariamente o jeito que o numpy exibe matrizes e vetores na tela
np.set_printoptions(formatter={'float': '{: >4.1f}'.format, 'int': '{: >2}'.format})

print(f"Matriz X:\n")
print(X_treino)
print(f"\nVetor y:\n")
print(y_treino)

print("\n")
print("-" * 10)
print("Testes do KNN")
print("-" * 10)

for num, instancia in enumerate(lista_de_testes, 1):
    # Formata o ponto para parecer um ponto cartesiano de verdade, ex: (2.0, 2.0)
    ponto_formatado = "(" + ", ".join([f"{val:.1f}" for val in instancia]) + ")"

    print(f"\nTESTE #{num}: Analisando o ponto {ponto_formatado}")
    print("-" * 10)

    for tipo_norma in ['l1', 'l2', 'inf']:
        resultado = classificador_knn(X_treino, y_treino, instancia, k=k_vizinhos, norma=tipo_norma)
        print(f"Norma: {tipo_norma.upper():<4} | Classe prevista: {resultado}")

    print("-" * 10)

print("\n")

ENTRADA DE DADOS
----------
[1] Fazer Upload de uma planilha do Excel (.xlsx)
[2] Usar dados simulados de teste automático (Sem precisar de arquivo)
----------
Digite a opção desejada (1 ou 2): 1

Por favor, faça o upload do seu arquivo Excel (.xlsx): 


Saving dados_treino_knn (2).xlsx to dados_treino_knn (2).xlsx
Arquivo 'dados_treino_knn (2).xlsx' carregado com sucesso!


[AVISO] Cabeçalho de texto detectado na matriz de dados. Removendo linha de títulos...
Matriz X:

[[ 2.2  1.9  2.3  2.8  1.9  1.9]
 [ 2.8  2.4  1.8  2.3  1.8  1.8]
 [ 2.1  1.0  1.1  1.7  1.5  2.2]
 [ 1.6  1.3  2.7  1.9  2.0  1.3]
 [ 1.7  2.1  1.4  2.2  1.7  1.9]
 [ 1.7  2.9  2.0  1.5  2.4  1.4]
 [ 2.1  1.0  1.3  2.1  2.4  2.1]
 [ 1.9  1.9  1.3  1.6  1.8  2.5]
 [ 2.2  1.1  2.2  1.8  1.7  2.3]
 [ 2.5  2.5  1.6  1.9  2.2  2.5]
 [ 1.8  1.9  1.4  1.4  2.4  2.7]
 [ 2.0  2.5  2.2  1.7  2.2  2.8]
 [ 2.0  2.8  0.7  2.4  2.0  1.9]
 [ 2.0  1.0  1.9  2.2  2.7  1.7]
 [ 1.6  1.8  2.5  2.2  1.7  2.3]
 [ 5.1  5.6  4.6  4.8  4.8  4.1]
 [ 5.2  5.2  5.0  4.9  4.2  4.8]
 [ 4.8  4.5  4.9  5.2  6.1  5.1]
 [ 5.2  5.0  3.9  5.0  5.0  6.5]
 [ 4.9  5.2  5.0  4.3  5.7  5.5]
 [ 5.5  4.5  5.8  4.2  5.3  6.3]
 [ 4.4  4.7  5.1  4.7  4.1  5.0]
 [ 4.4  5.3  4.5  5.9  4.5  4.8]
 [ 5.5  4.3  5.1  5.

In [3]:
# Questão 4


import pandas as pd       # Biblioteca para leitura de planilhas Excel (.xlsx)
import numpy as np        # Biblioteca para operações matemáticas e matrizes
from google.colab import files    # Biblioteca do Colab para upload de arquivos


# Funções algébricas


def exibir_polinomio_caracteristico(A):

  # Função para calcular e exibir o polinômio característico da matriz

    coeficientes = np.poly(A)   # Calcula os coeficientes do polinômio característico
    grau = len(coeficientes) - 1  # Descobre o grau do polinômio
    termos = []        # Lista que armazenará os termos formatados

    for i, coef in enumerate(coeficientes):

        grau_atual = grau - i
        coef_arred = round(coef, 4)

        if coef_arred == 0:
            continue

        sinal = "+ " if coef_arred > 0 and i > 0 else "- " if coef_arred < 0 and i > 0 else ""

        valor = abs(coef_arred)

        str_valor = "" if (valor == 1.0 and grau_atual > 0) else f"{valor}"

        if grau_atual == 0:
            termos.append(f"{sinal}{valor}")

        elif grau_atual == 1:
            termos.append(f"{sinal}{str_valor}λ")

        else:
            termos.append(f"{sinal}{str_valor}λ^{grau_atual}")

    return " ".join(termos) + " = 0"



def avaliar_autovetor(A, v, num_real, nome_vetor, tolerancia=1e-5):

  # Verifica se um vetor é autovetor de uma matriz para um λ informado

    v = v.flatten()     # Garante que o vetor esteja em formato unidimensional

    if np.allclose(v, 0, atol=tolerancia):
        return f"O vetor {nome_vetor} é nulo, portanto não é um autovetor por definição."

   # Calcula Av

    Av = A @ v
    lambda_v = num_real * v

    # Compara Av e λv considerando uma pequena tolerância numérica

    if np.allclose(Av, lambda_v, atol=tolerancia):
        return f"SIM! O vetor {nome_vetor} É um autovetor associado ao autovalor λ = {num_real}."

    return f"NÃO! O vetor {nome_vetor} NÃO é um autovetor associado ao autovalor λ = {num_real}."



def metodo_da_potencia(A, max_iter=100, tolerancia=1e-5):

  # Implementação do Método da Potência para encontrar o autovalor dominante

    n = A.shape[0]  # Obtem a dimensão da matriz

    x = np.ones(n)  # Vetor inicial de aproximação

    autovalor_antigo = 0.0   # Valor inicial do autovalor

    for _ in range(max_iter):

        x_novo = A @ x

        idx = np.argmax(np.abs(x_novo))

        autovalor_dominante = x_novo[idx] / x[idx]

        x_novo = x_novo / np.max(np.abs(x_novo))

        if np.abs(autovalor_dominante - autovalor_antigo) < tolerancia:
            break

        autovalor_antigo = autovalor_dominante
        x = x_novo

    return autovalor_dominante, x



# MENU DE ENTRADA DE DADOS

usar_dados_simulados = False
origem_dados = ""

while True:  # Loop principal do menu
    print("ENTRADA DE DADOS")
    print("----------")
    print("[1] Fazer Upload de uma planilha do Excel (.xlsx)")
    print("[2] Usar dados simulados de teste automático")
    print("----------")

    opcao = input("Digite a opção desejada (1 ou 2): ")

    if opcao == '1':
        print("\nPor favor, faça o upload do seu arquivo Excel (.xlsx):")

        # 1. Abre a janela para upload do arquivo (independente do nome)
        arquivos_enviados = files.upload()

        # Se o usuário cancelou ou não subiu nada
        if not arquivos_enviados:
            print("Nenhum arquivo foi enviado. Tente novamente...\n")
            continue
        else:
            # 2. Pega o nome do arquivo dinamicamente
            nome_arquivo = list(arquivos_enviados.keys())[0]

            try:
                # 3. Lê as abas usando o nome detectado automaticamente
                df_A = pd.read_excel(nome_arquivo, sheet_name='Matriz_A', header=None)
                df_b = pd.read_excel(nome_arquivo, sheet_name='Vetor_b', header=None)
                df_c = pd.read_excel(nome_arquivo, sheet_name='Vetor_c', header=None)
                df_P = pd.read_excel(nome_arquivo, sheet_name='Matriz_P', header=None)

                # 4. Converte para o formato matemático (NumPy) unificando os nomes
                matriz_A = df_A.to_numpy()
                matriz_P = df_P.to_numpy()
                vetor_b = df_b.to_numpy().flatten()
                vetor_c = df_c.to_numpy().flatten()

                print(f"\nArquivo '{nome_arquivo}' processado com sucesso!")
                origem_dados = "do Excel"
                break  # Sai do loop para executar os cálculos

            except Exception as e:
                print(f"\nErro ao processar o arquivo: {e}")
                print("Verifique se as abas internas do Excel se chamam: Matriz_A, Vetor_b, Vetor_c e Matriz_P\n")
                continue

    elif opcao == '2': #Para retornar algum dos autovetores SIM, usar lambda=12 ou 7
        print("\n[Modo Teste] Usando dados simulados...")
        # Matrizes e vetores utilizados para testes rápidos
        matriz_A = np.array([
            [12.0, 0.0, 0.0],
            [0.0, 7.0, 0.0],
            [0.0, 0.0, 5.0]
        ])
        vetor_b = np.array([1.0, 0.0, 0.0])
        vetor_c = np.array([0.0, 1.0, 0.0])
        matriz_P = np.array([
            [9.0, -1.0, 2.0],
            [-1.0, 10.0, -2.0],
            [1.0, -1.0, 12.0]
        ])

        print("Dados simulados carregados com sucesso!")
        origem_dados = "automáticos"
        break  # Sai do loop para executar os cálculos

    else:
        print("\n[OPÇÃO INVÁLIDA] Digite apenas 1 ou 2.\n")


#Tratamento de erros de tamanho da matriz

if matriz_A.shape[0] != matriz_A.shape[1]:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE FORMATO]")
    print("A matriz A precisa ser quadrada (n x n).")
    print(f"Dimensão encontrada: {matriz_A.shape}")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()

if len(vetor_b) != matriz_A.shape[0]:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE DIMENSÃO]")
    print("O vetor b possui tamanho incompatível")
    print("com a matriz A.")
    print(f"Dimensão de A: {matriz_A.shape}")
    print(f"Tamanho de b: {len(vetor_b)}")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()

if len(vetor_c) != matriz_A.shape[0]:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE DIMENSÃO]")
    print("O vetor c possui tamanho incompatível")
    print("com a matriz A.")
    print(f"Dimensão de A: {matriz_A.shape}")
    print(f"Tamanho de c: {len(vetor_c)}")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()


# IMPRESSÃO E EXECUÇÃO DOS CÁLCULOS

np.set_printoptions(
    formatter={
        'float': '{: >4.1f}'.format,
        'int': '{: >2}'.format
    }
)

print("\n" + "="*40)
print(f" DADOS CARREGADOS ({origem_dados.upper()})")
print("="*40)

print(f"\nMatriz A:")
print(matriz_A)

print(f"\nVetor b:")
print(vetor_b)

print(f"\nMatriz P:")
print(matriz_P)

print(f"\nVetor c:")
print(vetor_c)



# Entrada do autovalor
try:
    lambda_usuario = float(
        input("\nDigite o valor de λ para testar os autovetores: ")
    )

except ValueError:
    print("\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    print("[ERRO DE ENTRADA]")
    print("λ deve ser um valor numérico.")
    print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
    exit()



# Letra A
print("\n")
print("Letra A: Polinômio Característico")
print("-" * 30)
print(f"Polinômio P(λ) de A -> {exibir_polinomio_caracteristico(matriz_A)}")
print(f"Polinômio P(λ) de P -> {exibir_polinomio_caracteristico(matriz_P)}")
print("-" * 30)

# Letra B
print("\n")
print("Letra B: Avaliação de Autovetores")
print("-" * 30)
resultado_b = avaliar_autovetor(matriz_A, vetor_b, lambda_usuario, "b")
resultado_c = avaliar_autovetor(matriz_A, vetor_c, lambda_usuario, "c")
print(f"Vetor b: {resultado_b}")
print(f"Vetor c: {resultado_c}")
print("-" * 30)

# Letra C
print("\n")
print("Letra C: Método da Potência (Autovalor Dominante)")
print("-" * 30)
autovalor_dom, autovetor_dom = metodo_da_potencia(matriz_A)
ponto_formatado = "(" + ", ".join([f"{valor:.1f}" for valor in autovetor_dom]) + ")"
print(f"Autovalor dominante aproximado: {autovalor_dom:.2f}")
print(f"Autovetor dominante associado: {ponto_formatado}")
print("-" * 30)
print("\n")

ENTRADA DE DADOS
----------
[1] Fazer Upload de uma planilha do Excel (.xlsx)
[2] Usar dados simulados de teste automático
----------
Digite a opção desejada (1 ou 2): 1

Por favor, faça o upload do seu arquivo Excel (.xlsx):


Saving questao4(3).xlsx to questao4(3) (1).xlsx

Arquivo 'questao4(3) (1).xlsx' processado com sucesso!

 DADOS CARREGADOS (DO EXCEL)

Matriz A:
[[ 6  2  1]
 [ 0  5  3]
 [ 0  0  4]]

Vetor b:
[ 1  0  0]

Matriz P:
[[ 7  2  1]
 [ 1  8  2]
 [ 2  1  0]]

Vetor c:
[ 0  1  0]

Digite o valor de λ para testar os autovetores: 6


Letra A: Polinômio Característico
------------------------------
Polinômio P(λ) de A -> λ^3 - 15.0λ^2 + 74.0λ - 120.0 = 0
Polinômio P(λ) de P -> λ^3 - 15.0λ^2 + 50.0λ + 21.0 = 0
------------------------------


Letra B: Avaliação de Autovetores
------------------------------
Vetor b: SIM! O vetor b É um autovetor associado ao autovalor λ = 6.0.
Vetor c: NÃO! O vetor c NÃO é um autovetor associado ao autovalor λ = 6.0.
------------------------------


Letra C: Método da Potência (Autovalor Dominante)
------------------------------
Autovalor dominante aproximado: 6.00
Autovetor dominante associado: (1.0, 0.0, 0.0)
------------------------------


